---
spring:
  profiles: 'default'
server:
  port: '9000'
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:${server.port}/eureka'
      registerWithEureka: 'false'
      fetchRegistry: 'false'

---
server:
  port: '9001'
spring:
  profiles: 'united-states'
  application:
    name: 'eureka'
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:9001/eureka, http://localhost:9002/eureka'


---
server:
  port: '9002'
spring:
  profiles: 'france'
  application:
    name: 'eureka'
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:9001/eureka, http://localhost:9002/eureka'

